version: 2
updates:
  # Maintain Go dependencies (go.mod)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

    # reviewers:
    #   - "DrSkyle"

  # Maintain GitHub Actions (workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
